[package]
name = "analyzer"
version = "0.1.0"
authors = ["ebond <e.bondioli@todo.to.it>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.1"
